categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧹 Chores'
    labels: 
      - 'chore'
exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'chore'
    branch:
      - '/chore\/.+/'
      - '/docs\/.+/'
    body:
      - '/#chore/'
      - '/#docs/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    body:
      - '/#fix/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
    body:
      - '/#feature/'
  - label: 'skip-changelog'
    body:
      '/#skip-changelog/'
template: |
  ## What’s Changed

  $CHANGES